### fantastic packages and where to find them
---
- !package {name: MonetDBLite, ghub: hannesmuehleisen/MonetDBLite-R} 
- !package {name: dbplyr}
- !package {name: tidyverse}
- !package {name: clustermq}
- !package {name: susieR, ghub: stephenslab/susieR}
- !package {name: fs}
- !package {name: drake, ghub: ropensci/drake}
- !package {name: glue}
- !package {name: RSQLite}
- !package {name: vroom}
- !package {name: archive, ghub: jimhester/archive}
- !package {name: ldshrink, ghub: stephenslab/ldshrink}
- !package {name: daprcpp, ghub: CreRecombinase/daprr, ref: w_gsl}
- !package {name: ldmap, ghub: CreRecombinase/ldmap}
- !package {name: RSSp, ghub: CreRecombinase/RSSp}


