### workflow config
---
this: &this !root ["."]
data:
  home: &home "/scratch/midway2/nwknoblauch/"
  anno: !files { path: !path [*home , "ptb_scratch/new_bed"], glob: "**bed*" , type: "file", recurse: TRUE }
  ldetect: !file {path: !path [*home, "ldetect-data/EUR/",  "fourier_ls-all.tsv.gz"]}
  db: !file {path: !path [*home, "ptb_scratch/ga_gwas_monet.db/"] }
jobs: 5
nlines: -1
p_thresh: 1
num_loci: 15
memory_strategy: autoclean
caching: master
parallelism: clustermq
cache: !cache {file: !file {path: !path [*this, "cache/rcc"], check: FALSE} }

