### workflow config
---
this: &this !root ["."]
data:
  home: &home "/gpfs/data/xhe-lab/nwk"
  anno: !files { path: !path [*home , "ptb_scratch/new_bed"], glob: "**bed*" , type: "file", recurse: TRUE }
  ldetect: !file {path: !path [*home, "ldetect-data/EUR/",  "fourier_ls-all.tsv.gz"]}
  db: !file {path: !path [*home, "ptb_scratch/ga_gwas_monet.db/"] }
jobs: 3
nlines: -1
max_region_bp: 100000
max_snp: 10000
min_snp: 49
p_thresh: 0.05
num_loci: 10
memory_strategy: preclean
caching: master
parallelism: clustermq
cache: !cache {file: !file {path: !path [*this, "cache/gardner"], check: FALSE} }

